@API_HOST = http://localhost:8080/comments

### Get all stocks
GET {{API_HOST}}/ HTTP/1.1
Accept: application/json

###
GET {{API_HOST}}/2 HTTP/1.1
Accept: application/json

###
POST {{API_HOST}}/1
Content-Type: application/json

{
  "title": "First Comment",
  "content": "This is the content of the first comment."
}

###
DELETE {{API_HOST}}/3
Content-Type: application/json

###
PUT {{API_HOST}}/123
Content-Type: application/json

{
  "title": "Updatinggggggggggggg",
  "content": "This is the content of the first comment."
}